-- Complete database setup for the fitness app.
-- Safe to run more than once: it skips anything that already exists.
-- Run this first, then run 03-seed-places.sql.

-- ---------------------------------------------------------------------------
-- Who is allowed to manage content
-- ---------------------------------------------------------------------------
create table if not exists admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table admins enable row level security;

-- Must not query `admins` here, or the policy recurses into itself.
drop policy if exists "You can see your own admin row" on admins;
create policy "You can see your own admin row"
  on admins for select
  using (user_id = auth.uid());

-- Makes you an admin. Change the email if you signed up with a different one.
insert into admins (user_id)
select id from auth.users where email = 'dhruv2204goyal@gmail.com'
on conflict (user_id) do nothing;

-- ---------------------------------------------------------------------------
-- Places
-- ---------------------------------------------------------------------------
create table if not exists places (
  id bigint primary key generated by default as identity,
  osm_id bigint unique,
  name text not null,
  type text not null,
  area text,
  address text,
  lat double precision,
  lon double precision,
  fee text,
  rating numeric(2,1),
  phone text,
  timings text,
  amenities text[] not null default '{}',
  photo_url text,
  created_at timestamptz not null default now()
);

alter table places enable row level security;

drop policy if exists "Anyone can view places" on places;
create policy "Anyone can view places"
  on places for select using (true);

drop policy if exists "Admins can add places" on places;
create policy "Admins can add places"
  on places for insert
  with check (exists (select 1 from admins where user_id = auth.uid()));

drop policy if exists "Admins can edit places" on places;
create policy "Admins can edit places"
  on places for update
  using (exists (select 1 from admins where user_id = auth.uid()));

drop policy if exists "Admins can delete places" on places;
create policy "Admins can delete places"
  on places for delete
  using (exists (select 1 from admins where user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Events
-- ---------------------------------------------------------------------------
create table if not exists events (
  id bigint primary key generated by default as identity,
  name text not null,
  event_date date not null,
  venue text,
  organiser text,
  type text,
  description text,
  registration_url text,
  photo_url text,
  created_at timestamptz not null default now()
);

alter table events enable row level security;

drop policy if exists "Anyone can view events" on events;
create policy "Anyone can view events"
  on events for select using (true);

drop policy if exists "Admins can add events" on events;
create policy "Admins can add events"
  on events for insert
  with check (exists (select 1 from admins where user_id = auth.uid()));

drop policy if exists "Admins can edit events" on events;
create policy "Admins can edit events"
  on events for update
  using (exists (select 1 from admins where user_id = auth.uid()));

drop policy if exists "Admins can delete events" on events;
create policy "Admins can delete events"
  on events for delete
  using (exists (select 1 from admins where user_id = auth.uid()));

-- ---------------------------------------------------------------------------
-- Saved places
-- ---------------------------------------------------------------------------
create table if not exists favourites (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  place_id bigint not null,
  created_at timestamptz not null default now(),
  unique (user_id, place_id)
);

-- Widen the column if an older version of this table used a 4-byte integer.
alter table favourites alter column place_id type bigint;

alter table favourites enable row level security;

drop policy if exists "Users can view their own favourites" on favourites;
create policy "Users can view their own favourites"
  on favourites for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own favourites" on favourites;
create policy "Users can insert their own favourites"
  on favourites for insert with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own favourites" on favourites;
create policy "Users can delete their own favourites"
  on favourites for delete using (auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Event registrations
-- ---------------------------------------------------------------------------
create table if not exists event_registrations (
  id uuid primary key default gen_random_uuid(),
  user_id uuid not null references auth.users(id) on delete cascade,
  event_id bigint not null,
  created_at timestamptz not null default now(),
  unique (user_id, event_id)
);

alter table event_registrations alter column event_id type bigint;

alter table event_registrations enable row level security;

drop policy if exists "Users can view their own registrations" on event_registrations;
create policy "Users can view their own registrations"
  on event_registrations for select using (auth.uid() = user_id);

drop policy if exists "Users can insert their own registrations" on event_registrations;
create policy "Users can insert their own registrations"
  on event_registrations for insert with check (auth.uid() = user_id);

drop policy if exists "Users can delete their own registrations" on event_registrations;
create policy "Users can delete their own registrations"
  on event_registrations for delete using (auth.uid() = user_id);

-- Any rows here pointed at the three hardcoded sample events, whose ids would
-- now collide with real events.
delete from event_registrations;

-- ---------------------------------------------------------------------------
-- Shop click tracking
-- ---------------------------------------------------------------------------
create table if not exists product_clicks (
  id uuid primary key default gen_random_uuid(),
  user_id uuid references auth.users(id) on delete set null,
  product_id integer not null,
  clicked_at timestamptz not null default now()
);

alter table product_clicks enable row level security;

drop policy if exists "Users can view their own clicks" on product_clicks;
create policy "Users can view their own clicks"
  on product_clicks for select using (auth.uid() = user_id);

drop policy if exists "Anyone can record a click" on product_clicks;
create policy "Anyone can record a click"
  on product_clicks for insert
  with check (user_id is null or auth.uid() = user_id);

-- ---------------------------------------------------------------------------
-- Photo storage
-- ---------------------------------------------------------------------------
insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do nothing;

drop policy if exists "Anyone can view photos" on storage.objects;
create policy "Anyone can view photos"
  on storage.objects for select
  using (bucket_id = 'photos');

drop policy if exists "Admins can upload photos" on storage.objects;
create policy "Admins can upload photos"
  on storage.objects for insert
  with check (
    bucket_id = 'photos'
    and exists (select 1 from admins where user_id = auth.uid())
  );

drop policy if exists "Admins can replace photos" on storage.objects;
create policy "Admins can replace photos"
  on storage.objects for update
  using (
    bucket_id = 'photos'
    and exists (select 1 from admins where user_id = auth.uid())
  );

drop policy if exists "Admins can delete photos" on storage.objects;
create policy "Admins can delete photos"
  on storage.objects for delete
  using (
    bucket_id = 'photos'
    and exists (select 1 from admins where user_id = auth.uid())
  );
