-- Moves shop products into the database so they can be managed from the admin
-- area. Safe to run more than once.

create table if not exists products (
  id bigint primary key generated by default as identity,
  brand text not null,
  name text not null,
  price text,
  buy_url text not null,
  photo_url text,
  created_at timestamptz not null default now()
);

alter table products enable row level security;

drop policy if exists "Anyone can view products" on products;
create policy "Anyone can view products"
  on products for select using (true);

drop policy if exists "Admins can add products" on products;
create policy "Admins can add products"
  on products for insert
  with check (exists (select 1 from admins where user_id = auth.uid()));

drop policy if exists "Admins can edit products" on products;
create policy "Admins can edit products"
  on products for update
  using (exists (select 1 from admins where user_id = auth.uid()));

drop policy if exists "Admins can delete products" on products;
create policy "Admins can delete products"
  on products for delete
  using (exists (select 1 from admins where user_id = auth.uid()));

-- Product ids are now database-generated, so widen the click log to match.
alter table product_clicks alter column product_id type bigint;

-- Old clicks referenced the four hardcoded sample products.
delete from product_clicks;

-- Starting products, pointing at each brand's own site. Replace the links with
-- your affiliate links once your applications are approved.
insert into products (brand, name, price, buy_url)
select * from (values
  ('MuscleBlaze', 'Biozyme Whey Protein 1kg', '₹1,799', 'https://www.muscleblaze.com/'),
  ('Optimum Nutrition', 'Gold Standard 100% Whey 2lb', '₹3,499', 'https://www.optimumnutrition.com/en-us/'),
  ('Boldfit', 'Adjustable Dumbbell Set 20kg', '₹2,299', 'https://www.boldfit.in/'),
  ('HealthKart', 'HK Vitals Multivitamin (60 tabs)', '₹499', 'https://www.healthkart.com/')
) as seed(brand, name, price, buy_url)
where not exists (select 1 from products);
