-- Moves places and events into the database so they can be managed from the
-- app's admin area, and sets up photo storage.
-- Run this in the Supabase SQL Editor, then run 03-seed-places.sql.

-- Who is allowed to manage content.
create table admins (
  user_id uuid primary key references auth.users(id) on delete cascade,
  created_at timestamptz not null default now()
);

alter table admins enable row level security;

-- Must not query `admins` here, or the policy recurses into itself.
create policy "You can see your own admin row"
  on admins for select
  using (user_id = auth.uid());

-- Makes the current owner an admin. Replace the email if you use a different one.
insert into admins (user_id)
select id from auth.users where email = 'dhruv2204goyal@gmail.com';

-- Places. Seeded rows keep their OpenStreetMap id so existing favourites still
-- point at the right place; places you add yourself get small sequential ids.
create table places (
  id bigint primary key generated by default as identity,
  osm_id bigint unique,
  name text not null,
  type text not null,
  area text,
  address text,
  lat double precision,
  lon double precision,
  fee text,
  rating numeric(2,1),
  phone text,
  timings text,
  amenities text[] not null default '{}',
  photo_url text,
  created_at timestamptz not null default now()
);

alter table places enable row level security;

create policy "Anyone can view places"
  on places for select
  using (true);

create policy "Admins can add places"
  on places for insert
  with check (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can edit places"
  on places for update
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can delete places"
  on places for delete
  using (exists (select 1 from admins where user_id = auth.uid()));

-- Events.
create table events (
  id bigint primary key generated by default as identity,
  name text not null,
  event_date date not null,
  venue text,
  organiser text,
  type text,
  description text,
  registration_url text,
  photo_url text,
  created_at timestamptz not null default now()
);

alter table events enable row level security;

create policy "Anyone can view events"
  on events for select
  using (true);

create policy "Admins can add events"
  on events for insert
  with check (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can edit events"
  on events for update
  using (exists (select 1 from admins where user_id = auth.uid()));

create policy "Admins can delete events"
  on events for delete
  using (exists (select 1 from admins where user_id = auth.uid()));

-- Old registrations pointed at the three hardcoded sample events, whose ids
-- would now collide with real events. Clear that test data.
delete from event_registrations;

-- Photo storage.
insert into storage.buckets (id, name, public)
values ('photos', 'photos', true)
on conflict (id) do nothing;

create policy "Anyone can view photos"
  on storage.objects for select
  using (bucket_id = 'photos');

create policy "Admins can upload photos"
  on storage.objects for insert
  with check (
    bucket_id = 'photos'
    and exists (select 1 from admins where user_id = auth.uid())
  );

create policy "Admins can replace photos"
  on storage.objects for update
  using (
    bucket_id = 'photos'
    and exists (select 1 from admins where user_id = auth.uid())
  );

create policy "Admins can delete photos"
  on storage.objects for delete
  using (
    bucket_id = 'photos'
    and exists (select 1 from admins where user_id = auth.uid())
  );
